---
abstract: Perl extension for writing email autoresponders
author:
  - 'Adam Monsen <haircut@gmail.com>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Email-AutoReply
no_index:
  directory:
    - inc
    - t
recommends:
  Getopt::Declare: 0
requires:
  BerkeleyDB: 0
  Email::Address: 0
  Email::Send: 0
  Email::Simple: 0
  File::Path: 0
  Mail::ListDetector: 0
  Spiffy: 0.14
  perl: 5.8.3
version: 1.03
